export const TiposEscalabilidade: any = {
  1: 'Ponte',
  2: 'Sidechain',
  3: 'Rollup Otimista',
  4: 'Rollup ZK',
  5: 'Validium',
  6: 'Plasma',
  7: 'State Channel',
  1000: 'Todas',
} as const;

export const Blockchains: any = {
  1: 'Ethereum',
  2: 'Cronos', 
  3: 'Fantom',
  4: 'Cosmos',
  5: 'Polkadot',
  6: 'Polygon',
  7: 'Optimism',
  8: 'Arbitrum',
  9: 'Solana',
  10: 'BNB',
  11: 'Avalanche',
  12: 'Cartesi',
  13: 'Bitcoin',
  14: 'Gnosis',
  15: 'Near',
  16: 'Tron',
  1000: 'Todas',
} as const;

export const TipoMenu: any = {
  1: 'Escalabilidade',
  2: 'DEXs',
  3: 'Lending',
  4: 'Liquid Staking',
  5: 'NFTs',
} as const;

export const DefaultLinks: any = [
  {
    nome: 'Website',
    tipo: 2,
    imagem: '',
    icone: 'globe',
    bg: '#1B97F3',
    color: 'white',
    url: '',
  },
  {
    nome: 'Github',
    tipo: 1,
    imagem: 'git.svg',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Documentação',
    tipo: 2,
    imagem: '',
    icone: 'file-lines',
    bg: '#1C1B1F',
    color: 'white',
    url: '',
  },
  {
    nome: 'Blog',
    tipo: 2,
    imagem: '',
    icone: 'blog',
    bg: '#FFAD64',
    color: 'white',
    url: '',
  },
  {
    nome: 'Ecossistema',
    tipo: 2,
    imagem: '',
    icone: 'cubes',
    bg: '#5865F2',
    color: 'white',
    url: '',
  },
  {
    nome: 'Instagram',
    tipo: 1,
    imagem: 'insta.svg',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Telegram',
    tipo: 1,
    imagem: 'tel.svg',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Linkedin',
    tipo: 1,
    imagem: 'linkedin.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Reddit',
    tipo: 1,
    imagem: 'reddit.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Medium',
    tipo: 1,
    imagem: 'medium.webp',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Twitter',
    tipo: 1,
    imagem: 'twt.svg',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Discord',
    tipo: 1,
    imagem: 'disc.svg',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'YouTube',
    tipo: 1,
    imagem: 'yt.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'CoinGecko',
    tipo: 1,
    imagem: 'coingecko.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Coinmarketcap',
    tipo: 1,
    imagem: 'coinmarketcap.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Tradingview',
    tipo: 1,
    imagem: 'tradingview.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Binance',
    tipo: 1,
    imagem: 'binance.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Coinbase',
    tipo: 1,
    imagem: 'coinbase.svg',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Kucoin',
    tipo: 1,
    imagem: 'kucoin.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Bybit',
    tipo: 1,
    imagem: 'bybit.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'OKX',
    tipo: 1,
    imagem: 'okx.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Block Explorer',
    tipo: 1,
    imagem: 'scam.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Certik',
    tipo: 1,
    imagem: 'certik.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'DefiLlama',
    tipo: 1,
    imagem: 'defi.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Messari',
    tipo: 1,
    imagem: 'messari.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Dune Analytics',
    tipo: 1,
    imagem: 'dune.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Token Terminal',
    tipo: 1,
    imagem: 'tokent.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Dappradar',
    tipo: 1,
    imagem: 'dapr.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'L2 Beat',
    tipo: 1,
    imagem: 'l2.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Bubblemaps',
    tipo: 1,
    imagem: 'bubblemaps.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'TokenInsight',
    tipo: 1,
    imagem: 'tokeninsight.webp',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Cyberscan',
    tipo: 1,
    imagem: 'cyber.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
  {
    nome: 'Certfied',
    tipo: 1,
    imagem: 'certfied.png',
    icone: '',
    bg: '',
    color: '',
    url: '',
  },
] as const;